/*
** EPITECH PROJECT, 2023
** NWP_myteams_2023 [WSL : Ubuntu]
** File description:
** load_teams_library
*/

#pragma once

#define FUNC_MAX 39
#define CLIENT_EVENT_LOGGED_IN 0
#define CLIENT_EVENT_LOGGED_OUT 1
#define CLIENT_EVENT_PRIVATE_MESSAGE_RECEIVED 2
#define CLIENT_EVENT_THREAD_MESSAGE_RECEIVED 3
#define CLIENT_EVENT_TEAM_CREATED 4
#define CLIENT_EVENT_CHANNEL_CREATED 5
#define CLIENT_EVENT_THREAD_CREATED 6
#define CLIENT_PRINT_USERS 7
#define CLIENT_PRINT_TEAMS 8
#define CLIENT_TEAM_PRINT_CHANNELS 9
#define CLIENT_CHANNEL_PRINT_THREADS 10
#define CLIENT_THREAD_PRINT_REPLIES 11
#define CLIENT_PRIVATE_MESSAGE_PRINT_MESSAGES 12
#define CLIENT_ERROR_UNKNOWN_TEAM 13
#define CLIENT_ERROR_UNKNOWN_CHANNEL 14
#define CLIENT_ERROR_UNKNOWN_THREAD 15
#define CLIENT_ERROR_UNKNOWN_USER 16
#define CLIENT_ERROR_UNAUTHORIZED 17
#define CLIENT_ERROR_ALREADY_EXIST 18
#define CLIENT_PRINT_USER 19
#define CLIENT_PRINT_TEAM 20
#define CLIENT_PRINT_CHANNEL 21
#define CLIENT_PRINT_THREAD 22
#define CLIENT_PRINT_TEAM_CREATED 23
#define CLIENT_PRINT_CHANNEL_CREATED 24
#define CLIENT_PRINT_THREAD_CREATED 25
#define CLIENT_PRINT_REPLY_CREATED 26
#define CLIENT_PRINT_SUBSCRIBED 27
#define CLIENT_PRINT_UNSUBSCRIBED 28
#define SERVER_EVENT_TEAM_CREATED 29
#define SERVER_EVENT_CHANNEL_CREATED 30
#define SERVER_EVENT_THREAD_CREATED 31
#define SERVER_EVENT_REPLY_CREATED 32
#define SERVER_EVENT_USER_SUBSCRIBED 33
#define SERVER_EVENT_USER_UNSUBSCRIBED 34
#define SERVER_EVENT_USER_CREATED 35
#define SERVER_EVENT_USER_LOADED 36
#define SERVER_EVENT_USER_LOGGED_IN 37
#define SERVER_EVENT_USER_LOGGED_OUT 38
#define SERVER_EVENT_PRIVATE_MESSAGE_SENDED 39


int load_teams_library(char *pathtolib);